---
title: "Data-to-Graphs and Back: Project Page"
author: "VNV Rao"
date: "6/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to the Project

The 21st century world is one inundated with data. Everything from policy decisions to political strategies to advanced science to leisure pursuits such as streaming options are all based on data driven decisions. While complex analytics may be driving these processes, visualizations have proliferated throughout every day life as a new standard for individuals to consume information. From sports broadcasts to instagram pages about the Bachelor, modern data visualizations appear to be a mainstay for the coming years. 

Accordingly, statistics and data science curricula are adapting to teach students how to critically consume these modern data visualizations and also how to produce them. Yet the job of the teacher is no trivial thing. Teachers must not only consider how to teach (pedagogy), but also know what to teach (content), and be skilled in technology. This technical pedagogical content knowledge (TPCK) takes training and practice. 

To help inform the ways in which researchers can support teachers as they deliver modern data science curricula that include complex visualizations, this project investigates teachers' reasoning about the relationships between modern visualizations and their underlying data structures. 

# Data-to-Graphs and Back @ IASE 2021

[Our Abstract]()
[Our Poster](https://github.com/RaoVNV/Data-to-Graphs/blob/main/iase-2021-poster.pdf)


# Upcoming Paper in Preparation



